/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto;

import javax.swing.JOptionPane;

/**
 *
 * @author kevin
 */
public class asignarcurso extends javax.swing.JFrame {

    /**
     * Creates new form asignarcurso
     */
    public asignarcurso() {
        initComponents();
        jComboBox2.setEnabled(false);
        jComboBox2.setEditable(false);
        this.setLocationRelativeTo(null);
        for(Curso cu : Proyecto.cursos){
            jComboBox1.addItem(cu.nombre);
        }
       for(Alumnos a : Proyecto.alumnos){
            jComboBox2.addItem(Proyecto.AlumnosLogeado.nombre);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setText("Asignar");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel4.setText("Asignarse a Cursos");

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Salir");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Nimbus Sans", 3, 14)); // NOI18N
        jLabel1.setText("Curso:");

        jLabel2.setFont(new java.awt.Font("Nimbus Sans", 3, 14)); // NOI18N
        jLabel2.setText("Alumno:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel4)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
     /*   Curso empresaSeleccinada = null;
        Alumnos empleadoSeleccionado = null;
        
        for(Curso e : Proyecto.cursos){
            if(e.nombre.equals(jComboBox1.getSelectedItem().toString())){
                empresaSeleccinada = e;
                break;
            }
        }
        
      for(Alumnos e : Proyecto.alumnos){
            if(e.nombre.equals(jComboBox2.getSelectedItem().toString())){
                empleadoSeleccionado = Proyecto.AlumnosLogeado;
                break;
            }
        }
        
        if(empleadoSeleccionado!=null && empresaSeleccinada!=null){
            if(Proyecto.AlumnosLogeado.cursos.size()<5){
            empresaSeleccinada.alumnos.add(empleadoSeleccionado);
            empleadoSeleccionado.cursos.add(empresaSeleccinada);
            JOptionPane.showMessageDialog(this, "Curso asignado exitosamente.");
        }else{
                JOptionPane.showMessageDialog(this, "No se puede asignar a mas de 5 cursos.");
            }
        }*/
     // TODO add your handling code here:
        Curso cursoSeleccionado = null;
        Alumnos alumnoLogeado = Proyecto.AlumnosLogeado;

        // Buscar el curso seleccionado
        for (Curso e : Proyecto.cursos) {
            if (e.nombre.equals(jComboBox1.getSelectedItem().toString())) {
                cursoSeleccionado = e;
                break;
            }
        }

        if (cursoSeleccionado != null && alumnoLogeado != null) {
            // Verificar si el alumno ya está asignado a este curso
            if (alumnoLogeado.cursos.contains(cursoSeleccionado)) {
                JOptionPane.showMessageDialog(this, "Ya estás asignado a este curso.");
                return;
            }

            // Verificar si el curso ya tiene 10 estudiantes
            if (cursoSeleccionado.alumnos.size() >= 10) {
                JOptionPane.showMessageDialog(this, "Este curso ya tiene 10 estudiantes asignados.");
                return;
            }

            // Verificar si el alumno ya está asignado a 5 cursos
            if (alumnoLogeado.cursos.size() >= 5) {
                JOptionPane.showMessageDialog(this, "No se puede asignar a más de 5 cursos.");
                return;
            }

            // Asignar el curso al alumno y el alumno al curso
            cursoSeleccionado.alumnos.add(alumnoLogeado);
            alumnoLogeado.cursos.add(cursoSeleccionado);
            JOptionPane.showMessageDialog(this, "Curso asignado exitosamente.");
        }
            
        


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        BienvenidaAlumno l = new BienvenidaAlumno();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
