/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto;

import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author kevin
 */
public class ConsultaCursos extends javax.swing.JFrame {

    public ConsultaCursos() {
        initComponents();
        this.setLocationRelativeTo(null);
        actualizarTabla();
    }

    private void actualizarTabla() {
        this.setLocationRelativeTo(null);

        DefaultTableModel data = new DefaultTableModel(new String[]{"ID", "Nombre", "Sección", "F.Inicio", "F.Fin", "H.Inicio", "H.Fin", "Profesor"}, Proyecto.cursos.size());
        jTable1.setModel(data);

        int row = 0;

        for (Curso cu : Proyecto.cursos) {
            jTable1.setValueAt(cu.id, row, 0);
            jTable1.setValueAt(cu.nombre, row, 1);
            jTable1.setValueAt(cu.seccion, row, 2);
            jTable1.setValueAt(cu.fechainicio, row, 3);
            jTable1.setValueAt(cu.fechafin, row, 4);
            jTable1.setValueAt(cu.horainicio, row, 5);
            jTable1.setValueAt(cu.horafin, row, 6);
            //jTable1.setValueAt(cu.profe, row, 7);
            //jTable1.setValueAt(cu.notafinal, row, 8);

            String nombreEmpresa = "";
            for (profesor p : Proyecto.profesores) {
                if (p.cursos.contains(cu)) {
                    nombreEmpresa = p.nombre;
                    break;
                }
            }
            jTable1.setValueAt(nombreEmpresa, row, 7);
            row++;

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel4.setText("Consulta de Cursos");

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Actualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Carga Masiva .JSON");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel4)))
                .addContainerGap(267, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ModificarCurso mac = new ModificarCurso(jTable1.getSelectedRow());
        mac.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        actualizarTabla();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            leer(selectedFile.getPath());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

public void leer(String rutaConNombre) {
        JSONParser jp = new JSONParser();
        try {
            FileReader r = new FileReader(rutaConNombre);
            Object obj = jp.parse(r);
            JSONArray cursosList = (JSONArray) obj;

            DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

            for (Object c : cursosList) {
                JSONObject cursoObj = (JSONObject) c;
                long id = (long) cursoObj.get("id");
                String nombre = (String) cursoObj.get("nombre");
                String seccion = (String) cursoObj.get("seccion");
                String fechaInicio = (String) cursoObj.get("fecha_inicio");
                String fechaFin = (String) cursoObj.get("fecha_fin");
                String horaInicio = (String) cursoObj.get("hora_inicio");
                String horaFin = (String) cursoObj.get("hora_fin");
                String profesor = (String) cursoObj.get("profesor");

                // Crear objeto Curso y agregarlo a la lista
                Curso curso = new Curso();
                curso.id = (int) id;
                curso.nombre = nombre;
                curso.seccion = seccion;
                curso.fechainicio = fechaInicio;
                curso.fechafin = fechaFin;
                curso.horainicio = horaInicio;
                curso.horafin = horaFin;
                curso.profe = profesor;

                Proyecto.cursos.add(curso);

                // Agregar fila a la tabla
                tableModel.addRow(new Object[]{id, nombre, seccion, fechaInicio, fechaFin, horaInicio, horaFin, profesor});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

     


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
