/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kevin
 */
public class consultacurso extends javax.swing.JFrame {

    /**
     * Creates new form consultacurso
     */
    public consultacurso() {
        initComponents();
       this.setLocationRelativeTo(null);

                  actualizarTabla();
}

private void actualizarTabla(){ 
                Alumnos empleadoSeleccionado = null;
                empleadoSeleccionado =  Proyecto.AlumnosLogeado;
                
                 
                

        
        if(empleadoSeleccionado!=null){
      
        DefaultTableModel data = new DefaultTableModel(new String[]{"ID","Nombre","Sección","F.Inicio","F.Fin","H.Inicio","H.Fin","Profesor","Nota Final"},empleadoSeleccionado.cursos.size());
        jTable1.setModel(data);
        
        int row=0;
        
        for(Curso e : empleadoSeleccionado.cursos){
            jTable1.setValueAt(e.id, row, 0);
            jTable1.setValueAt(e.nombre, row, 1);  
            jTable1.setValueAt(e.seccion, row, 2);
            jTable1.setValueAt(e.fechainicio, row, 3);
            jTable1.setValueAt(e.fechafin, row, 4);  
            jTable1.setValueAt(e.horainicio, row, 5);
            jTable1.setValueAt(e.horafin, row, 6);
            String nombreEmpresa = "";
            for(profesor p :Proyecto.profesores){
                if(p.cursos.contains(e)){
                    nombreEmpresa = p.nombre;
                    break;
                }
            }
            jTable1.setValueAt(nombreEmpresa, row, 7);
             double notaAlumno = e.nota;
            jTable1.setValueAt(notaAlumno, row, 8);

            row++;
           

            }
        }
               
               
            
        
        
   /*     Alumnos alumnoActual = null;
        if(Proyecto.AlumnosLogeado instanceof Alumnos){
            alumnoActual = (Alumnos) Proyecto.AlumnosLogeado;

            if (alumnoActual != null){
                DefaultTableModel data = new DefaultTableModel(new String []{"ID","Nombre","Sección","F.Inicio","F.Fin","H.Inicio","H.Fin","Profesor","Nota Final"},Proyecto.cursos.size());
                jTable1.setModel(data);
                
                int row = 0;
                
                for(Curso c : alumnoActual.cursos){
                   
            jTable1.setValueAt(c.id, row, 0);
            jTable1.setValueAt(c.nombre, row, 1);  
            jTable1.setValueAt(c.seccion, row, 2);
            jTable1.setValueAt(c.fechainicio, row, 3);
            jTable1.setValueAt(c.fechafin, row, 4);  
            jTable1.setValueAt(c.horainicio, row, 5);
            jTable1.setValueAt(c.horafin, row, 6);
                   String  nombreProfesor = "";
                   for(profesor p : Proyecto.profesores){
                       if(p.cursos.contains(c)){
                           nombreProfesor = p.nombre;
                           break;
                       }
                   }
                   jTable1.setValueAt(nombreProfesor, row, 7);
                   
                   double notaAlumno = alumnoActual.Nota;
                   jTable1.setValueAt(notaAlumno, row, 8);
                   
                   row ++;
                }
            }
            
        }    */       
               
               
               
               
               
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Desasignarme del Curso");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("C059", 3, 18)); // NOI18N
        jLabel2.setText("Mis Cursos Asignados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel2)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        BienvenidaAlumno l = new BienvenidaAlumno();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        int row = jTable1.getSelectedRow();
        
        Alumnos empleadoSeleccionado = Proyecto.AlumnosLogeado;
        empleadoSeleccionado.cursos.remove(row);
        
        
        String name = jTable1.getModel().getValueAt(row, 1).toString();        
        for(Curso c: Proyecto.cursos){
            
            if(c.nombre.equals(name))
            {
                c.alumnos.remove(empleadoSeleccionado);
            }
        }
        
        actualizarTabla();
        JOptionPane.showMessageDialog(this, "Desasignacion exitosa");

    }//GEN-LAST:event_jButton2ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
